AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  PgpLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pgplambda.lambda_handler
      CodeUri: src
      Runtime: python3.9
      Timeout: 300
      MemorySize: 128
